### PR TITLE
Retry getting credentials from Boto3

### LINKED ISSUE #2581: Toil 3.19 release fails CWLTest.test_run_s3 trying to get_frozen_credentials on None
See the test log here:

https://ucsc-ci.com/databiosphere/toil/-/jobs/6397

```
=================================== FAILURES ===================================
_____________________________ CWLTest.test_run_s3 ______________________________
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 111, in test_run_s3
    self.download('download_s3.json', self._tester)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 99, in download
    self._expected_download_output(self.outDir))
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/test/cwl/cwlTest.py", line 71, in _tester
    cwltoil.main(main_args, stdout=st)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/cwl/cwltoil.py", line 1254, in main
    import_files(initialized_job_order)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/cwl/cwltoil.py", line 1232, in import_files
    skip_broken=True))
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 47, in adjustFileObjs
    visit_class(rec, ("File",), op)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/cwltool/utils.py", line 210, in visit_class
    visit_class(rec[d], cls, op)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/cwltool/utils.py", line 208, in visit_class
    op(rec)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/cwl/cwltoil.py", line 365, in uploadFile
    uploadfunc, fileindex, existing, uf["location"])
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/cwl/cwltoil.py", line 337, in write_file
    index[x] = "toilfs:" + writeFunc(rp)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/common.py", line 953, in importFile
    return self._jobStore.importFile(srcUrl, sharedFileName=sharedFileName)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/jobStores/abstractJobStore.py", line 299, in importFile
    return self._importFile(otherCls, srcUrl, sharedFileName=sharedFileName, hardlink=hardlink)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/jobStores/fileJobStore.py", line 272, in _importFile
    sharedFileName=sharedFileName)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/jobStores/abstractJobStore.py", line 320, in _importFile
    otherCls._readFromUrl(url, writable)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/jobStores/aws/jobStore.py", line 435, in _readFromUrl
    srcKey = cls._getKeyForUrl(url, existing=True)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/jobStores/aws/jobStore.py", line 476, in _getKeyForUrl
    with closing(boto.connect_s3()) as s3:
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/boto/connection.py", line 555, in __init__
    profile_name)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/__init__.py", line 491, in __init__
    profile_name=profile_name, **kwargs)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/local/lib/python2.7/site-packages/boto/provider.py", line 201, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/__init__.py", line 503, in get_credentials
    self._obtain_credentials_from_cache_or_boto3()
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/__init__.py", line 620, in _obtain_credentials_from_cache_or_boto3
    self._obtain_credentials_from_boto3()
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/__init__.py", line 545, in _obtain_credentials_from_boto3
    creds.get_frozen_credentials()
AttributeError: 'NoneType' object has no attribute 'get_frozen_credentials'
```

This clearly has something to do with my AWS credentials hacking.

### PR DESCRIPTION
**Pull request by adamnovak**
It may make network requests that can fail.

Also, we want a good error message if it fails, and not a complaint about operating on None.

Fixes #2581 hopefully

### CODE REVIEW

**Comment by adamnovak** [comment]
I saw the same failure in Python 3'a `testWriteGzipLogs` test as we saw in #2566.

```
=================================== FAILURES ===================================
_______________________ RegularLogTest.testWriteGzipLogs _______________________
Traceback (most recent call last):
  File "/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/src/toil/test/src/regularLogTest.py", line 76, in testWriteGzipLogs
    stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/gitlab-runner/builds/WgJTr25x/0/databiosphere/toil/venv/bin/python', '-m', 'toil.test.mesos.helloWorld', './toilTest', '--clean=always', '--logLevel=debug', '--writeLogsGzip=/tmp/toil-test-toil.test.src.regularLogTest.RegularLogTest-testWriteGzipLogs-tempDir-f37fk4a8']' returned non-zero exit status 1.
```

I'm going to run the Pyhton 3 tests again; this seems to be an intermittent error unrelated to what I'm doing right now, but debigging it is hard, as it appears to be gzipping up the logs instead of sending them to us.

**Comment by adamnovak** [comment]
OK, I weirdly can't retry the python 3 job. When I say to restart it, the resulting pending job says it is stuck due to there not being any runners assigned, while the runner happily chuugs along past it and runs other jobs.

**Comment by adamnovak** [comment]
The real fix for #2981 is the role on the Gitlab runner on EC2; this PR just improves error reporting a bit.

**Comment by adamnovak** [comment]
This PR has the encoding fix for CWLTest.test_run_s3; I need to pull it over into #2595. That PR will look weird until this one is merged.
