### ISSUE TITLE
GPU support broken on SingleMachine?

### ISSUE THREAD

**Issue by glennhickey** [DataBiosphere/toil#4503]
This came up here: https://github.com/ComparativeGenomicsToolkit/cactus/issues/1062

The error is 
```
 File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 604, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'
```
and seems due to the fact that accelerator_set is a `ResourcePool` when the method in qestion is a member of `ResourceSet`.  

This issue occurs in v5.10.0 and v5.11.0 but not v5.9.0.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1351)
┆Issue Number: TOIL-1351

**Comment by adamnovak** [comment]
I think I have a PR for this in #4506. I did indeed break this without noticing.

**Comment by thiagogenez** [comment]
I'm still getting this error with the lastest Cactus version `2.6.4` @adamnovak 

I'm trying to see where the problem is, but no success so far.

```
[2023-07-19T16:28:40+0100] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/9492; your environment may be out of spec!
[2023-07-19T16:28:40+0100] [MainThread] [I] [toil.worker] Redirecting logging to /tmp/a66d7510cbf45b558efa6bfe6117d1b7/a2e1/worker_log.txt
[2023-07-19T16:28:57+0100] [MainThread] [I] [toil.leader] Issued job 'LastzRepeatMaskJob' kind-LastzRepeatMaskJob/instance-y8spqe_f v1 with job batch system ID: 11 and disk: 9.5 Gi, memory: 4.0 Gi, cores: 48, accelerators: [{'count': 4, 'kind': 'gpu', 'api': 'cuda', 'brand': 'nvidia'}], preemptible: True
[2023-07-19T16:28:57+0100] [Thread-1  ] [C] [toil.batchSystems.singleMachine] Unhandled exception in daddy thread for batch system 140283176224656: Traceback (most recent call last):
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 229, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 605, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 229, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 605, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'
[2023-07-19T16:28:59+0100] [MainThread] [C] [toil.batchSystems.singleMachine] Propagating unhandled exception in daddy thread to main thread
[2023-07-19T16:29:02+0100] [MainThread] [I] [toil.realtimeLogger] Stopping real-time logging server.
[2023-07-19T16:29:02+0100] [MainThread] [I] [toil.realtimeLogger] Joining real-time logging server thread.
[2023-07-19T16:29:02+0100] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/9492; your environment may be out of spec!
[2023-07-19T16:29:02+0100] [MainThread] [W] [toil.common] XDG_RUNTIME_DIR is set to nonexistent directory /run/user/9492; your environment may be out of spec!
Traceback (most recent call last):
  File "/home/cactus/cactus_env/bin/cactus-preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 545, in main
    stageWorkflow(outputSequenceDir=None,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/cactus/preprocessor/cactus_preprocessor.py", line 380, in stageWorkflow
    outputSequenceIDs = toil.start(unzip_job)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1064, in start
    return self._runMainLoop(rootJobDescription)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/common.py", line 1511, in _runMainLoop
    return Leader(config=self.config,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 251, in run
    self.innerLoop()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/leader.py", line 749, in innerLoop
    updatedJobTuple = self.batchSystem.getUpdatedBatchJob(maxWait=2)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 834, in getUpdatedBatchJob
    self._checkOnDaddy()
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 288, in _checkOnDaddy
    raise exc
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 229, in daddy
    result = self._startChild(jobCommand, jobID,
  File "/home/cactus/cactus_env/lib/python3.8/site-packages/toil/batchSystems/singleMachine.py", line 605, in _startChild
    snapshot = accelerator_set.get_free_snapshot()
AttributeError: 'ResourcePool' object has no attribute 'get_free_snapshot'
```

**Comment by glennhickey** [comment]
@thiagogenez @mr-c 

While this issue as been resolved in Toil, it will not make it into Cactus until 

1) There is a new Toil release that includes the patch (presumably 5.12)
2) A new Cactus release is made that links to this new Toil release.

@thiagogenez If you want to use gpu in single machine on Cactus v2.6.4 in the meantime, you must patch Toil yourself.  You can do this by simply downgrading to Toil version 5.9.0.  Alternately, you can test the new patch by installing Toil's master branch. (you can do all this via `pip install` in your cactus virtual environment, including inside any container).

**Comment by thiagogenez** [comment]
Just help whoever working with Cactus `v2.6.4` using `singularity`, the following commands allow replicating the mentioned patch https://github.com/DataBiosphere/toil/commit/45bc3f4d7d110753b00ee0014d761a34bdc7a8ab

```bash
# pulls and builds cactus image 
singularity build cactus.sif docker://quay.io/comparative-genomics-toolkit/cactus:v2.6.4  

# converts the container to writable sandbox
singularity build --sandbox cactus_sandbox/ cactus.sif 

# apply the path
sed -i 's/\[3\]/\[-1\]/g' cactus_sandbox/home/cactus/cactus_env/lib/python3.10/site-packages/toil/batchSystems/singleMachine.py

# converts from sandbox to container
singularity build cactus-patch.sif cactus_sandbox/ 
```

**Comment by adamnovak** [comment]
Looks like we had better make a Toil release.

**Comment by DailyDreaming** [comment]
@adamnovak @thiagogenez @glennhickey New release is out.
