### ISSUE TITLE
Toil fails on python 3.7 due to dependency

### ISSUE THREAD

**Issue by diekhans** [DataBiosphere/toil#2924]
Toil has an indirect dependency on  http_parser package which is no longer maintained on pypi (last update 2013).  This package does not compile with python 3.7.  It is required by pymesos

However, it does not appear that pymesos has released a version that corrects this.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-489)
┆Issue Number: TOIL-489

**Comment by diekhans** [comment]
ticket filed on pymesos:
https://github.com/douban/pymesos/issues/122

**Comment by adamnovak** [comment]
I think `pymesos` is only pulled in by the mesos extra. A workaround might be to install without the mesos extra (i.e. not `toil[all]` or `toil[mesos]`).

Sadly this won't work when building the appliance; it kind of has to support mesos.

**Comment by diekhans** [comment]
I am changing Cactus not include mesos for now, although if you do:

    CPPFLAGS='-DPYPY_VERSION' pip install http_parser

it actually compiles (not sure if it works).  also,

    pip install git+https://github.com/benoitc/http-parser.git

work too.

sigh

**Comment by interfect** [comment]
I can't replicate `pip install git+https://github.com/benoitc/http-parser.git` working on 3.7. It still fails with a bunch of errors like:

```
    http_parser/parser.c:7038:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /opt/local/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
```

I'll see if any of the open PRs fix it.

**Comment by adamnovak** [comment]
I can't replicate pip install git+https://github.com/benoitc/http-parser.git working on 3.7. It still fails with a bunch of errors like:

```
    http_parser/parser.c:7038:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?
        tstate->exc_traceback = local_tb;
                ^~~~~~~~~~~~~
                curexc_traceback
    /opt/local/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here
        PyObject *curexc_traceback;
                  ^
```

I'll see if any of the open PRs fix it.

**Comment by diekhans** [comment]
Odd it didn't work for you.  I tried that because it was recommend by someone in cyberspace

Using 

  CPPFLAGS='-DPYPY_VERSION'

does work, as it avoids the problem code path.

Really, pymesos shouldn't be using a DOA package ;-(

**Comment by adamnovak** [comment]
The reason it didn't work was that I had an old version of Cython installed, which the http-parser build process decided to use to produce broken versions of its bindings.

I have a PR open to http-parser to set it up to require a compatible Cython when installing from a non-release version, and I think I can pull that in as part of Toil's Mesos extra and pymesos will just use it.

**Comment by diekhans** [comment]
I think we should leave this open until we had a permanent fix.

**Comment by diekhans** [comment]
I have created a ticket for http_parser: https://github.com/benoitc/http-parser/issues/90
