### PR TITLE
Cactus compatibility fixes

### LINKED ISSUE #2854: Latest toil no longer works with cactus
A cactus command that works in version 3.20 now gives this error with master (I'm using a newer toil to test kubernetes for cactus).  It's strange because `Job._runner()` has a `defer` argument in the [source](https://github.com/DataBiosphere/toil/blob/master/src/toil/job.py#L1371-L1375):
```
INFO:toil.worker:Redirecting logging to /data1/cactus/toil-6141c5d4-202b-4550-a160-4d43177be980-565d6e0ff41b452899bd1cc744672e86/tmpj9fnaA/worker_log.txt
Job ended: 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instanceICGaXj
The job seems to have left a log file, indicating failure: 'RunCactusPreprocessorThenProgressiveDown' kind-RunCactusPreprocessorThenProgressiveDown/instanceICGaXj
INFO:toil:Running Toil version 3.21.0a1-81a543d0e1a8e6c299f22bb8e862d34097e1f0bc.
WARNING:toil.resource:'JTRES_612c0b9862883c5800042ea7ac702778' may exist, but is not yet referenced by the worker (KeyError from os.environ[]).
Traceback (most recent call last):
  File "/data1/cactus/toil-venv-master/local/lib/python2.7/site-packages/toil/worker.py", line 366, in workerScript
    job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore, defer=defer)
TypeError: _runner() got an unexpected keyword argument 'defer'
ERROR:toil.worker:Exiting the worker because of a failed job on host ip-172-31-26-21
```

This can be reproduced in a minute with these commands:
```
deactivate
git clone https://github.com/DataBiosphere/toil.git toil.master
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
cd cactus
virtualenv toil-venv-master
. toil-venv-master/bin/activate
pip install ../toil.master[all]
pip install .
toil clean jobStore ; cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal  --binariesMode docker --batchSystem singleMachine --workDir .
```

Doing the same thing with the last release runs okay
```
# Works with toil 3.20
deactivate
git clone https://github.com/DataBiosphere/toil.git toil.320
pushd toil.320 ;  git checkout cf34ca3416697f2abc816b2538f20ee29ba16932 ; popd
git clone https://github.com/ComparativeGenomicsToolkit/cactus.git --recursive
cd cactus
virtualenv toil-venv-320
. toil-venv-320/bin/activate
pip install ../toil.320[all]
pip install .
toil clean jobStore ; cactus jobStore examples/evolverMammals.txt examples/evolverMammals.hal  --binariesMode docker --batchSystem singleMachine --workDir .
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-451)
┆Issue Number: TOIL-451

### PR DESCRIPTION
**Pull request by adamnovak**
Should fix #2854 by adapting Toil to still allow some of the things that Cactus does that we no longer allow.

This *should*, so far, allow Cactus to keep passing around strings as file IDs, by letting the FileStore recover file size information from the JobStore when it isn't passed along with the ID.

### CODE REVIEW

**Comment by adamnovak** [comment]
A Cactus test is a good idea. @glennhickey Can you suggest something?

**Comment by bollig** [comment]
So what is the solution to get this update? Looks like the fix was merged into master. No new version has been released.

**Comment by adamnovak** [comment]
Right now the way to get these fixes is to build your own Toil Docker image, or use the one @glennhickey has been using with this in it.

But instead of waiting for that you can also go back to Toil 3.20, which predates the restrictions that we added that Cactus doesn't obey. Only Toil 3.21 is affected by the problem being fixed here.
